In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [24]:
# load datasets
data=pd.read_csv("Churn_Modelling.csv")
data.head

<bound method NDFrame.head of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]>

In [25]:
# preprocess the data
# drop irrelevant columns

data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [26]:
# ab dekho ki agr koi aisa data h jisko encode krne kijaruruat h 
# like categorical way me male female,yes no aisa type
# kyuki model ko number smjh ata h names nhi..isisliye 
# baaki number columns h wo apen aap smjh lega

label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [27]:
# here on geography column we will apply ohe we cant do
# labelencoder as it is a having other the 2 value,so 
# model will make unnecessary heirarchy

from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
ohe_geo=ohe.fit_transform(data[['Geography']])
ohe_geo.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [28]:
ohe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [97]:
# yaha maine features name ke column banaye aur usme vectorized georgrpahy daldiya
geo_df=pd.DataFrame(ohe_geo.toarray(),columns=ohe.get_feature_names_out(['Geography']))

In [32]:
data=pd.concat([data.drop('Geography',axis=1),geo_df],axis=1)

In [30]:
# now we will save the robot which are labelEncoder and OneHotEncoder
# into pickle file

with open ('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('ohe.pkl','wb') as file:
    pickle.dump(ohe,file)

In [ ]:
# now we will separate the dependet and independent features

x=data.drop('Exited',axis=1)
y=data['Exited']

# split the data in training and testing sets
# x_train + y_train → model.fit() → model seekhta hai
# x_test → model.predict() → guess karta hai
# y_test → actual answer
# compare → accuracy

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# scale these features mtlb same unit me lana taki moel confuse na ho ki mtr bada h cm se for eg

scaler=StandardScaler()
x_train = scaler.fit_transform(x_train)  # learn + apply kyuki x traijn se hi na trianing krna h to fit transform taki wo learn or apply kre..
# x test me sirf apply krnah kyuki uss etest krna h usko learn nhi krwana h soch ke dekh...iska ans dega tbhina pata chlega shi bana h
x_test = scaler.transform(x_test)

In [35]:
x_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [36]:
with open('scaler.pkl',"wb") as file:
    pickle.dump(scaler,file)

In [37]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [39]:
x_train.shape[1]

12

In [40]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [41]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    # hidden layer 1 connected to input layer
    Dense(32,activation='relu'),
    # hl2
    Dense(1,activation='sigmoid')
    # output layer
])

WARNING:tensorflow:From c:\UDEMY\ANN CLASSIFICATION\venv\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [42]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [43]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [44]:
# compiling the model
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [ ]:
# set up the tensorboard for log visual thorugh grpah
log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [56]:
# setting up earlystopping 
early_stopping_callbacks=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [62]:
# troin the model
model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,callbacks=[tensorflow_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2048 - accuracy: 0.9025 - val_loss: 0.7132 - val_accuracy: 0.8480
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2009 - accuracy: 0.9007 - val_loss: 0.7448 - val_accuracy: 0.8475
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1978 - accuracy: 0.9034 - val_loss: 0.7001 - val_accuracy: 0.8450
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1941 - accuracy: 0.9049 - val_loss: 0.7501 - val_accuracy: 0.8455
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1899 - accuracy: 0.9060 - val_loss: 0.7374 - val_accuracy: 0.8440
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1991 - accuracy: 0.9018 - val_loss: 0.7693 - val_accuracy: 0.8400
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1963 - accuracy: 0.9022 - val_loss: 0.7765 - val_accuracy: 0.8465
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2003 - accuracy: 0.9036 - val_loss: 0.7983 - val_accuracy: 0.8480
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1963 - accuracy: 0.9029 - val_loss: 0.7634 - val_accuracy: 0.8455
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.1877 - accuracy: 0.9039 - val_loss: 0.7651 - val_accuracy: 0.8425
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1932 - accuracy: 0.9031 - val_loss: 0.8560 - val_accuracy: 0.8450
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1954 - accuracy: 0.9034 - val_loss: 0.8006 - val_accuracy: 0.8445
Epoch 13/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1908 - accuracy: 0.9061 - val_loss: 0.8655 - val_accuracy: 0.8455
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1958 - accuracy: 0.9039 - val_loss: 0.7878 - val_accuracy: 0.8460
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1919 - accuracy: 0.9045 - val_loss: 0.7951 - val_accuracy: 0.8420
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1837 - accuracy: 0.9064 - val_loss: 0.8365 - val_accuracy: 0.8495
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1859 - accuracy: 0.9059 - val_loss: 0.8346 - val_accuracy: 0.8405
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1942 - accuracy: 0.9039 - val_loss: 0.8781 - val_accuracy: 0.8500
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1877 - accuracy: 0.9057 - val_loss: 0.8593 - val_accuracy: 0.8425
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1817 - accuracy: 0.9055 - val_loss: 0.9765 - val_accuracy: 0.8410
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2110 - accuracy: 0.9000 - val_loss: 0.8214 - val_accuracy: 0.8445
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2066 - accuracy: 0.8995 - val_loss: 0.8342 - val_accuracy: 0.8460
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1909 - accuracy: 0.9039 - val_loss: 0.7892 - val_accuracy: 0.8450
Epoch 24/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1901 - accuracy: 0.9022 - val_loss: 0.8514 - val_accuracy: 0.8430
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1854 - accuracy: 0.9062 - val_loss: 0.8513 - val_accuracy: 0.8450
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1878 - accuracy: 0.9035 - val_loss: 0.8301 - val_accuracy: 0.8450
Epoch 27/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1815 - accuracy: 0.9049 - val_loss: 0.8855 - val_accuracy: 0.8485
Epoch 28/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1787 - accuracy: 0.9062 - val_loss: 0.8942 - val_accuracy: 0.8525
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1768 - accuracy: 0.9066 - val_loss: 0.8477 - val_accuracy: 0.8420
Epoch 30/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1842 - accuracy: 0.9064 - val_loss: 0.8288 - val_accuracy: 0.8470
Epoch 31/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1823 - accuracy: 0.9061 - val_loss: 0.8795 - val_accuracy: 0.8435
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1771 - accuracy: 0.9050 - val_loss: 0.8700 - val_accuracy: 0.8425
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1823 - accuracy: 0.9051 - val_loss: 0.8970 - val_accuracy: 0.8465
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1789 - accuracy: 0.9068 - val_loss: 0.9006 - val_accuracy: 0.8420
Epoch 35/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1827 - accuracy: 0.9056 - val_loss: 0.9298 - val_accuracy: 0.8475
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1858 - accuracy: 0.9035 - val_loss: 0.8722 - val_accuracy: 0.8395
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1804 - accuracy: 0.9087 - val_loss: 0.8545 - val_accuracy: 0.8415
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1809 - accuracy: 0.9056 - val_loss: 0.9088 - val_accuracy: 0.8440
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1856 - accuracy: 0.9061 - val_loss: 0.9225 - val_accuracy: 0.8460
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1766 - accuracy: 0.9061 - val_loss: 0.8909 - val_accuracy: 0.8490
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1730 - accuracy: 0.9072 - val_loss: 0.9273 - val_accuracy: 0.8470
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1789 - accuracy: 0.9061 - val_loss: 0.9311 - val_accuracy: 0.8475
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1800 - accuracy: 0.9061 - val_loss: 0.9790 - val_accuracy: 0.8360
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1837 - accuracy: 0.9036 - val_loss: 0.8883 - val_accuracy: 0.8065
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1784 - accuracy: 0.9072 - val_loss: 0.9856 - val_accuracy: 0.8445
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1804 - accuracy: 0.9076 - val_loss: 1.0574 - val_accuracy: 0.8470
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1746 - accuracy: 0.9060 - val_loss: 0.9460 - val_accuracy: 0.8475
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1889 - accuracy: 0.9049 - val_loss: 0.9073 - val_accuracy: 0.8385
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1745 - accuracy: 0.9044 - val_loss: 0.9961 - val_accuracy: 0.8470
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1713 - accuracy: 0.9093 - val_loss: 0.9704 - val_accuracy: 0.8450
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1677 - accuracy: 0.9101 - val_loss: 1.0544 - val_accuracy: 0.8430
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1706 - accuracy: 0.9103 - val_loss: 0.9594 - val_accuracy: 0.8455
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1750 - accuracy: 0.9082 - val_loss: 1.0593 - val_accuracy: 0.8475
Epoch 54/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1800 - accuracy: 0.9075 - val_loss: 0.9733 - val_accuracy: 0.8460
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1797 - accuracy: 0.9072 - val_loss: 0.9142 - val_accuracy: 0.8505
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1810 - accuracy: 0.9071 - val_loss: 1.0242 - val_accuracy: 0.8415
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1783 - accuracy: 0.9054 - val_loss: 0.9764 - val_accuracy: 0.8105
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1807 - accuracy: 0.9068 - val_loss: 1.0111 - val_accuracy: 0.8430
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1768 - accuracy: 0.9064 - val_loss: 0.9250 - val_accuracy: 0.8460
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1674 - accuracy: 0.9075 - val_loss: 1.0401 - val_accuracy: 0.8450
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1633 - accuracy: 0.9095 - val_loss: 1.0567 - val_accuracy: 0.8450
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1671 - accuracy: 0.9074 - val_loss: 1.0185 - val_accuracy: 0.8430
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1705 - accuracy: 0.9105 - val_loss: 1.0147 - val_accuracy: 0.8440
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1772 - accuracy: 0.9076 - val_loss: 1.0666 - val_accuracy: 0.8385
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1831 - accuracy: 0.9080 - val_loss: 0.9147 - val_accuracy: 0.8410
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1752 - accuracy: 0.9075 - val_loss: 1.0622 - val_accuracy: 0.8420
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1756 - accuracy: 0.9096 - val_loss: 1.0643 - val_accuracy: 0.8395
Epoch 68/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1705 - accuracy: 0.9081 - val_loss: 1.0146 - val_accuracy: 0.8420
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1738 - accuracy: 0.9074 - val_loss: 0.9960 - val_accuracy: 0.8340
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1658 - accuracy: 0.9105 - val_loss: 1.1204 - val_accuracy: 0.8075
Epoch 71/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1753 - accuracy: 0.9051 - val_loss: 1.0666 - val_accuracy: 0.8100
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1698 - accuracy: 0.9062 - val_loss: 0.9933 - val_accuracy: 0.8005
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1714 - accuracy: 0.9095 - val_loss: 0.9681 - val_accuracy: 0.8035
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1767 - accuracy: 0.9068 - val_loss: 1.0764 - val_accuracy: 0.8425
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1736 - accuracy: 0.9124 - val_loss: 1.0944 - val_accuracy: 0.8390
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1674 - accuracy: 0.9097 - val_loss: 1.0727 - val_accuracy: 0.8450
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1653 - accuracy: 0.9068 - val_loss: 1.1270 - val_accuracy: 0.8445
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1601 - accuracy: 0.9129 - val_loss: 1.1302 - val_accuracy: 0.8065
Epoch 79/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1670 - accuracy: 0.9082 - val_loss: 1.1089 - val_accuracy: 0.8415
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1717 - accuracy: 0.9086 - val_loss: 1.0782 - val_accuracy: 0.8420
Epoch 81/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1725 - accuracy: 0.9069 - val_loss: 1.1424 - val_accuracy: 0.8440
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1689 - accuracy: 0.9046 - val_loss: 1.0164 - val_accuracy: 0.8430
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1700 - accuracy: 0.9090 - val_loss: 1.0529 - val_accuracy: 0.8055
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1659 - accuracy: 0.9061 - val_loss: 1.0227 - val_accuracy: 0.8145
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1643 - accuracy: 0.9079 - val_loss: 1.1487 - val_accuracy: 0.8495
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1629 - accuracy: 0.9095 - val_loss: 1.0334 - val_accuracy: 0.8040
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1696 - accuracy: 0.9086 - val_loss: 1.1453 - val_accuracy: 0.8065
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1640 - accuracy: 0.9078 - val_loss: 1.0879 - val_accuracy: 0.8425
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1568 - accuracy: 0.9124 - val_loss: 1.1080 - val_accuracy: 0.8045
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1579 - accuracy: 0.9155 - val_loss: 1.0771 - val_accuracy: 0.7990
Epoch 91/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1654 - accuracy: 0.9129 - val_loss: 1.1077 - val_accuracy: 0.7925
Epoch 92/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1606 - accuracy: 0.9119 - val_loss: 1.1524 - val_accuracy: 0.8175
Epoch 93/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1662 - accuracy: 0.9100 - val_loss: 1.1763 - val_accuracy: 0.8450
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1655 - accuracy: 0.9110 - val_loss: 1.0866 - val_accuracy: 0.8415
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1599 - accuracy: 0.9119 - val_loss: 1.1771 - val_accuracy: 0.8055
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1605 - accuracy: 0.9150 - val_loss: 1.0595 - val_accuracy: 0.7985
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1705 - accuracy: 0.9118 - val_loss: 1.0947 - val_accuracy: 0.8020
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1648 - accuracy: 0.9089 - val_loss: 1.1727 - val_accuracy: 0.8130
Epoch 99/100
250/250 [==============================] - 1s 2ms/step - loss: 0.1644 - accuracy: 0.9125 - val_loss: 1.2651 - val_accuracy: 0.8025
Epoch 100/100
250/250 [==============================] - 1s 3ms/step - loss: 0.1636 - accuracy: 0.9118 - val_loss: 1.1109 - val_accuracy: 0.7955

In [63]:
model.save('model.h5')

c:\UDEMY\ANN CLASSIFICATION\venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [68]:
# load tensor board extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [69]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 25976), started 0:17:37 ago. (Use '!kill 25976' to kill it.)

In [70]:
from tensorflow.keras.models import load_model
import numpy as np

In [ ]:
# now here we willl load all the trained model,pickle file of ohe gender and label enocder geo

model=load_model('model.h5')

with open('ohe.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)


with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)    

with open('scaler.pkl','rb') as file:
    scaler_load=pickle.load(file)

In [72]:
# now we will take the sample input

input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [ ]:
# now we will encode geo here first as it it required
geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray( )
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\UDEMY\ANN CLASSIFICATION\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [86]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [87]:
# now we will encode gender
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [88]:
# now we will concat the geo with the input df

input_df=pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [ ]:
# s aling the input now
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [92]:
# prediction of churn

prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 26ms/step

array([[1.0258722e-15]], dtype=float32)

In [94]:
prediction_prob=prediction[0][0]
prediction_prob

1.0258722e-15

In [95]:
if prediction_prob > 0.5:
   print('customer is likely to churn')
else:
   print('cusotomer is not likely to churn')

cusotomer is not likely to churn

In [ ]:
# DATA LOAD → CLEAN → ENCODE (Gender + Geography)
# → SAVE ENCODERS
# → SPLIT (TRAIN/TEST)
# → SCALE DATA
# → BUILD MODEL (ANN)
# → COMPILE
# → TRAIN (fit)
# → SAVE MODEL

# PREDICTION SIDE:
# LOAD MODEL + ENCODERS + SCALER
# → RAW INPUT
# → ENCODE
# → SCALE
# → PREDICT
# → RESULT